mill1000/midea-ac-py

custom_components/midea_ac/config_flow.py
custom_components/midea_ac/translations/en.json

Originally noticed in #22, we were displaying all found devices on the network even if they weren't supported.
Close #24

Update config flow to not allow configuration of unsupported devices

---

custom_components/midea_ac/config_flow.py
custom_components/midea_ac/strings.json
custom_components/midea_ac/translations/en.json

Abort the config flow when auto config fails due to a connection failure.
Close #35

Abort config flow on failed auto configuration

---

custom_components/midea_ac/climate.py

`is_on`, `async_turn_on` and `async_turn_off` are not part of the climate platform so removing them.

Remove invalid property and methods for climate platform

---

custom_components/midea_ac/__init__.py
custom_components/midea_ac/climate.py
custom_components/midea_ac/coordinator.py
custom_components/midea_ac/number.py

Use device capabilities to intelligently populate available fan speeds. On devices that support it, add a custom fan speed control via a number entity.
Also, reduce de-bounce on coordinator to make number and climate response better.
Close #40

Intelligently populate fan speed options and add support for custom fan speeds

---

custom_components/midea_ac/climate.py

Intelligently populate the climate entity's supported features property based on the capabilities of the device

Only display swing mode features if device supports a swing mode

---

custom_components/midea_ac/__init__.py

After adding the number component in #45, we forgot to unload the number component.
Additionally we switched the global key for the coorindate from CONF_ID to the entry_id, which caused the unload task to fail to remove the coordinator

Fix async_unload_entry

---

custom_components/midea_ac/climate.py
custom_components/midea_ac/services.yaml
custom_components/midea_ac/strings.json
custom_components/midea_ac/translations/en.json

* Add a custom service to control the "follow me" feature introduced in https://github.com/mill1000/midea-msmart/pull/91
* Expose the current "follow me" state in an attribute of the climate entity.
The justification for using a service over a switch is to obscure the feature slightly due to the following reasons.
* There is no capability to determine if this function exists. Without a capability we can't decide when to create a "follow me" switch entity intelligently. Otherwise we would hide the feature behind an integration option.
* Usage of this feature isn't straightforward and is very device specific.
Close #49 and related to https://github.com/mill1000/midea-msmart/issues/89

Add a service to control "follow me" feature

---

README.md
custom_components/midea_ac/translations/it.json

italian translation

---

README.md
custom_components/midea_ac/translations/pt.json

Add Portuguese translation

---

custom_components/midea_ac/climate.py
custom_components/midea_ac/sensor.py

Close #77 
UnitOfTemperature was introduced about a year ago, so I'm not concerned about dropping the TEMP_ constants and breaking too many years.

Replace deprecated usage of TEMP_ constants

---

custom_components/midea_ac/binary_sensor.py
custom_components/midea_ac/climate.py
custom_components/midea_ac/number.py
custom_components/midea_ac/sensor.py
custom_components/midea_ac/switch.py

Update entity naming to match current recommended conventions. 
References:
- https://developers.home-assistant.io/blog/2023/06/28/entity-name-changes/
- https://developers.home-assistant.io/blog/2022/07/10/entity_naming/
- https://developers.home-assistant.io/docs/core/entity/#entity-naming
Hopefully fixes #74

Update entity naming conventions

---

custom_components/midea_ac/__init__.py

Raise ConfigEntryNotReady instead of ConfigEntryAuthFailed when authentication failed.
This seems counterintuitive, but AuthFailed tries to start a flow to allow a user to re-auth. In our case, auth failures are more likely a network issue so raising NotReady should cause it to try again later.
Close #93 and hopefully help with #90

Raise ConfigEntryNotReady when setup fails

---

custom_components/midea_ac/climate.py

The implicit handlers caused the HVAC mode to change to HEAT. Close #97

Define explicit turn_off/turn_on handlers

---

custom_components/midea_ac/__init__.py
custom_components/midea_ac/config_flow.py

In forthcoming msmart-ng releases, the authenticate method will throw exceptions on authentication failure (https://github.com/mill1000/midea-msmart/pull/113) .
Update the config flow and init to handle these exceptions

Handle excetions from device authentication

---

custom_components/midea_ac/__init__.py
custom_components/midea_ac/icons.json
custom_components/midea_ac/select.py
custom_components/midea_ac/translations/en.json

Add select entities to control the horizontal and vertical swing angle for devices that support the feature.
Requires https://github.com/mill1000/midea-msmart/pull/109
Close #69

Add support for controlling swing angle on supported devices

---

custom_components/midea_ac/__init__.py

This will ensure the lifetime applies to the first connection created.

Set connection lifetime before device is authenticated

---

custom_components/midea_ac/__init__.py

https://developers.home-assistant.io/blog/2024/06/12/async_forward_entry_setups

Avoid deprecated method `async_forward_entry_setup`

---

custom_components/midea_ac/coordinator.py
custom_components/midea_ac/manifest.json
custom_components/midea_ac/sensor.py
custom_components/midea_ac/translations/en.json

Add humidity and energy sensors for supported devices.
Energy sensors are disabled by default and must be enabled.
Close #5 
Close #86 
Indirectly close #81, as msmart-ng 2024.7.1 will suppress those warnings.

Add humidity  and energy sensors

---

custom_components/midea_ac/binary_sensor.py

Reverts mill1000/midea-ac-py#176
CONFIG is not valid for a binary sensor

Revert "Change filter alert entity category so it can be used in area cards"

---

README.md
custom_components/midea_ac/__init__.py
custom_components/midea_ac/binary_sensor.py
custom_components/midea_ac/button.py
custom_components/midea_ac/icons.json
custom_components/midea_ac/translations/en.json

Add button and binary sensor for active/self clean function of supported devices.
Requires https://github.com/mill1000/midea-msmart/pull/149
Untested

Add self/active clean support

---

custom_components/midea_ac/sensor.py

Incorrect assumed it was in KW due to a comment in the reference code.
Close #194

Switch real time power unit to Watts

---

custom_components/midea_ac/sensor.py

Call super's `async_added_to_hass()` in energy sensors to ensure lifecycle is properly handled.
Without this call, the sensors are not updated likely because the Update Coordinator does not know about them.
Close #201

Fix unavailable energy sensors

---

custom_components/midea_ac/manifest.json

Contains necessary updates to support #209 and #205

Bump msmart-ng to 2024.8.0

---

README.md
custom_components/midea_ac/icons.json
custom_components/midea_ac/select.py
custom_components/midea_ac/translations/en.json

Adds support for "gear" or "rate select" on supported devices.
Should also support "generator mode" which allows the user to select between 5 levels of power usage.
Requires https://github.com/mill1000/midea-msmart/pull/157

Add gear/rate select support

---

custom_components/midea_ac/translations/hr.json

Becouse no HR words for this type of use words will be in english. If I found something better I will update the translation.
Changes to be committed:
modified:   custom_components/midea_ac/translations/hr.json

Add HR translation for "Breeze away", "Breeze mild" and "Breezeless".

---

custom_components/midea_ac/manifest.json

Changes notes from release
* Catch request exceptions from httpx by @mill1000 in https://github.com/mill1000/midea-msmart/pull/163
* Remove Optional type hint on "supports" properties. by @mill1000 in https://github.com/mill1000/midea-msmart/pull/164
* Fix inability to turn off breeze modes by @mill1000 in https://github.com/mill1000/midea-msmart/pull/165
* Add device-level capabilities tests by @mill1000 in https://github.com/mill1000/midea-msmart/pull/166
**Full Changelog**: https://github.com/mill1000/midea-msmart/compare/2024.8.0...2024.8.1

Bump msmart-ng to 2024.8.1

---

custom_components/midea_ac/__init__.py
custom_components/midea_ac/binary_sensor.py
custom_components/midea_ac/button.py
custom_components/midea_ac/climate.py
custom_components/midea_ac/number.py
custom_components/midea_ac/select.py
custom_components/midea_ac/sensor.py
custom_components/midea_ac/switch.py

The original purpose of those was to ensure compatibility with older msmart releases.
Since we are now maintaining msmart-ng we can ensure the properties exist

Replace getattr/hasattr usage with direct property access.

---

custom_components/midea_ac/climate.py

Updated deprecated properties

---

custom_components/midea_ac/manifest.json

Change notes from msmart-ng 2024.9.0
* Resolve occasional exceptions in user logs by catching CancelledError by @mill1000 in https://github.com/mill1000/midea-msmart/pull/167
* Use enum for "breeze" mode by @mill1000 in https://github.com/mill1000/midea-msmart/pull/169
* Add IECO support by @mill1000 in https://github.com/mill1000/midea-msmart/pull/162
* Refactor property decode/encode by @mill1000 in https://github.com/mill1000/midea-msmart/pull/170
* Refactor preset properties to avoid "_mode" prefix which may have been conflated with operational modes by @mill1000 in https://github.com/mill1000/midea-msmart/pull/171
* Add alternate energy/power response parsing by @mill1000 in https://github.com/mill1000/midea-msmart/pull/172

Bump msmart-ng to 2024.9.0

---

custom_components/midea_ac/diagnostics.py

Add the diagnostics platform to the integration.
This adds the "download diagnostics" button to the device page and allows dumping some useful information about the device.
Currently included is 
- the config entry
- basic device info like IP, Port, ID, etc
- the various detected supported features
Close #235

Add diagnostics support

---

custom_components/midea_ac/select.py

Due to a misuse of `is not` the rate select entity was being created even if the device did not support rate select

Rate select should only be visible when device supports more than 1 rate

---

custom_components/midea_ac/__init__.py
custom_components/midea_ac/config_flow.py

Migrate old config entries as needed. Used https://github.com/home-assistant/core/pull/127732 as a reference.
Close #250

Ensure unique_id is a string

---

custom_components/midea_ac/translations/pl.json

Update Polish translation

---

custom_components/midea_ac/config_flow.py

Update the config and options flow with some QoL improvements and to resolve a deprecation warning from HA.
- Remove hidden text input for Token
- Retain host and cloud region when discovering a single device if it fails
- Use `add_suggested_values_to_schema` instead of manually populating defaults and suggested values

Update config and options flow

---

custom_components/midea_ac/config_flow.py
custom_components/midea_ac/const.py
custom_components/midea_ac/coordinator.py

Some users needed values less than 30 seconds, effectively creating a new connection for every update. #283

Reduce minimium connection lifetime to 15 seconds

---

custom_components/midea_ac/coordinator.py
tests/test_coordinator.py

Possible fix for #300, and may solve some users issues reported in #254

Put a lock around calls to device refresh() to prevent concurrent calls from throwing exceptions

---

README.md
custom_components/midea_ac/diagnostics.py
custom_components/midea_ac/icons.json
custom_components/midea_ac/select.py
custom_components/midea_ac/translations/en.json

Adds select entity for controlling electric auxiliary heat modes.
Close #297 
Requires an update to msmart-ng

Add support for auxillary heat modes

---

custom_components/midea_ac/manifest.json

Relevant changes:
* Let cloud errors propagate when fetching tokens during discovery by @mill1000 in https://github.com/mill1000/midea-msmart/pull/203
* Switch to NetHome Plus cloud to restore get_token and discovery functionality by @mill1000 in https://github.com/mill1000/midea-msmart/pull/194
*  Update discovery flow to throw exceptions when cloud connection fails by @mill1000 in https://github.com/mill1000/midea-msmart/pull/197

Bump msmart-ng to 2025.3.1

---

custom_components/midea_ac/config_flow.py
custom_components/midea_ac/translations/en.json

Add a new dummy step to the discovery config flow that displays the device's ID, token and key. Users should copy this information to a safe place in case the cloud service goes offline.
All user input on this form is discarded.
Close #331

Add a dummy step to the discovery flow to display token & key from device

---

custom_components/midea_ac/manifest.json

Should close #148 
* Fixed calculation of temperature with decimals by @gaspo in https://github.com/mill1000/midea-msmart/pull/177
* Update pyproject licensing to be compliant with PEP 639 by @mill1000 in https://github.com/mill1000/midea-msmart/pull/209

Bump msmart-ng to 2025.3.3

---

custom_components/midea_ac/climate.py

This prevents transmission of SetProperties commands to devices without support as seen in #338 . Close #338

Only set the iECO device property if supported

---

custom_components/midea_ac/manifest.json

Required to support #371 
* Fix bad Cascade unit test by @mill1000 in https://github.com/mill1000/midea-msmart/pull/227
* Skip Cloud tests when running on CI by @mill1000 in https://github.com/mill1000/midea-msmart/pull/226
* Use class instead of ID to filter for specific responses by @mill1000 in https://github.com/mill1000/midea-msmart/pull/228
* Raise exceptions on connection lost events by @mill1000 in https://github.com/mill1000/midea-msmart/pull/229
* Add support for accessing individual energy data fields in either format by @mill1000 in https://github.com/mill1000/midea-msmart/pull/230

Bump msmart-ng to 2025.9.0

---

custom_components/midea_ac/config_flow.py
tests/test_config_flow.py

In #374 a user configured an unsupported device type. I don't know for sure if it was via the manual flow but we should try to prevent this.
Close #377

Reject unsupported devices during manual configuration

---

custom_components/midea_ac/manifest.json

* Add device type check to Frame.validate method by @mill1000 in https://github.com/mill1000/midea-msmart/pull/239
* Update device online/supported logic by @mill1000 in https://github.com/mill1000/midea-msmart/pull/240
* Remove use of deprecated properties in to_dict by @mill1000 in https://github.com/mill1000/midea-msmart/pull/231
* Validate frame length by @mill1000 in https://github.com/mill1000/midea-msmart/pull/236
* Extract and expose error code from StateResponse by @mill1000 in https://github.com/mill1000/midea-msmart/pull/238

Bump msmart-ng to 2025.9.2
