- custom_components/midea_ac/climate.py
Add support for sleep preset in Cool, Heat and Auto modes.
> Add support for sleep preset

- custom_components/midea_ac/climate.py
Only support ECO preset in cool, dry and auto mode. Close #2
> Only expose ECO preset in supported modes.

- .github/workflows/hacs.yml
- .github/workflows/hassfest.yml
- custom_components/midea_ac/manifest.json
https://hacs.xyz/docs/publish/include#before-submitting
> Add required HACS actions for inclusion in default list.

- custom_components/midea_ac/sensor.py
Update sensor component to display unknown temperature values as Unavailable
> Display temperature sensors as unavailable when unavailable

- custom_components/midea_ac/manifest.json
Update to msmart-ng 2023.9.4 to fix cloud account issue
> Update manifest for 2023.9.4 release

- README.md
- custom_components/midea_ac/translations/pl.json
Thanks to @Theo16
Requires #55
> Add Polish translation.

- README.md
- custom_components/midea_ac/translations/hr.json
> Add Croation translations.

- README.md
- custom_components/midea_ac/translations/ko.json
Added Korean(한국어) translations
> docs: translated with Korean

- custom_components/midea_ac/manifest.json
Should close #67 and also resolve some mismatch capabilities users have reported
> Update to msmart-ng 2023.12.0

- custom_components/midea_ac/climate.py
> Replace magic SUPPORT_ numbers with ClimateEntityFeature

- README.md
- custom_components/midea_ac/translations/nl.json
> Add Dutch translation

- custom_components/midea_ac/climate.py
> Add new ClimateEntityFeature flags for HA 2024.2

- custom_components/midea_ac/__init__.py
> Fix missing import for ConfigEntryNotReady

- custom_components/midea_ac/manifest.json
Update msmart-ng to 2024.3.1. Hopefully solves #101
> Bump msmart-ng to 2024.3.1

- custom_components/midea_ac/manifest.json
> Bump msmart-ng to 2024.3.2

- README.md
- custom_components/midea_ac/translations/ro.json
> Add Romanian translation

- custom_components/midea_ac/translations/it.json
> Update italian translation.json

- custom_components/midea_ac/translations/hu.json
Translating the new positions.
I've rewritten it into formal Hungarian to match Home Assistant, from an informal mode.
> Update Hungarian translation

- custom_components/midea_ac/translations/pl.json
> Update Polish translations

- custom_components/midea_ac/switch.py
Requires msmart-ng 2024.5.1
Close #120
> Add switch entity to control Anion function

- custom_components/midea_ac/manifest.json
> Update msmart-ng version to 2024.5.1

- custom_components/midea_ac/manifest.json
> Bump msmart-ng to 2024.5.4

- custom_components/midea_ac/binary_sensor.py
- custom_components/midea_ac/number.py
- custom_components/midea_ac/select.py
- custom_components/midea_ac/sensor.py
- custom_components/midea_ac/switch.py
- custom_components/midea_ac/translations/en.json
https://github.com/mill1000/midea-ac-py/issues/54#issuecomment-2200592043
Add support for translating the remaining entity names.
> Add support for translating additional entity names

- README.md
- custom_components/midea_ac/translations/ru.json
> Add Russian translations.

- custom_components/midea_ac/translations/pl.json
> Update Polish translation

- custom_components/midea_ac/translations/nl.json
> Update Dutch translation

- custom_components/midea_ac/translations/ro.json
> Update Romainian translation

- custom_components/midea_ac/translations/hr.json
> Update Croation translations

- custom_components/midea_ac/translations/zh-Hans.json
> Add Simplified Chinese translation.

- README.md
- custom_components/midea_ac/translations/zh-Hant.json
> Add Traditional Chinese translation

- README.md
- custom_components/midea_ac/translations/sl.json
> Add Slovenian translation

- custom_components/midea_ac/binary_sensor.py
> Only add filter sensor if it's supported

- custom_components/midea_ac/translations/en.json
In order to support https://github.com/mill1000/midea-msmart/pull/145
> Add translation for MAX fan speed

- custom_components/midea_ac/binary_sensor.py
> Change filter alert entity category so it can be used in area cards

- custom_components/midea_ac/binary_sensor.py
Redo of https://github.com/mill1000/midea-ac-py/pull/176 , fixes https://github.com/mill1000/midea-ac-py/issues/175
> Remove entity category from filter alert

- README.md
- custom_components/midea_ac/climate.py
Support setting target humidity in DRY mode when device supports it
Requires https://github.com/mill1000/midea-msmart/pull/144
> Add support for setting target humidity

- custom_components/midea_ac/translations/hr.json
> Update Croatian translation

- custom_components/midea_ac/translations/sk.json
Fix filter alert translation based on feedback from https://github.com/mill1000/midea-ac-py/pull/159#issuecomment-2235861353
> Update Slovak translation

- README.md
- custom_components/midea_ac/icons.json
- custom_components/midea_ac/switch.py
- custom_components/midea_ac/translations/en.json
Add various "breeze" modes like
* Breeze away
* Breeze mild
* Breezeless/silky cool
Requires https://github.com/mill1000/midea-msmart/pull/159
Close #186
> Add "breeze" modes

- custom_components/midea_ac/translations/hr.json
Added HR Translation for Gear Select.
> Add HR translation for gear / rate selects

- README.md
- custom_components/midea_ac/climate.py
- custom_components/midea_ac/const.py
- custom_components/midea_ac/icons.json
- custom_components/midea_ac/translations/en.json
Close #218 
Requires https://github.com/mill1000/midea-msmart/pull/162
> Add iECO to presets when supported

- custom_components/midea_ac/climate.py
> Fix swing_mode regression from #222

- README.md
- custom_components/midea_ac/translations/fr.json
> Add French translation

- custom_components/midea_ac/translations/it.json
Add missing Italian translations and align existing ones. Contributes to #54
> chore: italian translation

- README.md
- custom_components/midea_ac/translations/eu.json
> Add Basque translation.

- custom_components/midea_ac/translations/hr.json
Changes to be committed:
modified:   custom_components/midea_ac/translations/hr.json
Added missing HR translations to hr.json
> Added missing HR translations to hr.json

- custom_components/midea_ac/climate.py
> Fix `set_temperature` action which didn't respect `hvac_mode` argument

- README.md
- custom_components/midea_ac/translations/no.json
> Add Norwegian translation

- .devcontainer/devcontainer.json
- .github/workflows/checks.yml
- custom_components/midea_ac/coordinator.py
- pytest.ini
- tests/__init__.py
- tests/conftest.py
- tests/requirements.txt
- tests/test_config_flow.py
- tests/test_coordinator.py
Add a few test cases for the integration. Utilize https://github.com/MatthewFlamm/pytest-homeassistant-custom-component to make it all work.
> Add unit tests

- custom_components/midea_ac/manifest.json
Change log from release
> ## What's Changed
> * Add device ID to log messages to improve debugging multuiple devicest at once by @mill1000 in https://github.com/mill1000/midea-msmart/pull/187
> * Add support auxilary/electric/emergency heat by @mill1000 in https://github.com/mill1000/midea-msmart/pull/185
> * Add missing DEFAULT value for AuxHeat enum by @mill1000 in https://github.com/mill1000/midea-msmart/pull/188
> * Keep device online if any command received a response by @mill1000 in https://github.com/mill1000/midea-msmart/pull/189
> Bump msmart-ng to 2025.2.0

- custom_components/midea_ac/manifest.json
> Bump msmart-ng to 2025.2.1

- custom_components/midea_ac/config_flow.py
Requires https://github.com/mill1000/midea-msmart/pull/191
Fixes #311
> Use HA helper to get httpx AsyncClient for discovery

- README.md
- custom_components/midea_ac/config_flow.py
- custom_components/midea_ac/translations/en.json
- tests/test_config_flow.py
> Add checks for invalid token/key format in manual configuration

- README.md
- custom_components/midea_ac/diagnostics.py
- custom_components/midea_ac/icons.json
- custom_components/midea_ac/switch.py
- custom_components/midea_ac/translations/en.json
Close #343, requires https://github.com/mill1000/midea-msmart/pull/212
> Add support for flash/jet cool

- custom_components/midea_ac/manifest.json
Release notes
* Mask fan speed by 0x7F by @mill1000 in https://github.com/mill1000/midea-msmart/pull/219
> Bump msmart-ng to 2025.5.1

- custom_components/midea_ac/icons.json
> Add icons for Max and Silent fan speeds

- custom_components/midea_ac/select.py
- custom_components/midea_ac/translations/en.json
> Add support for Cascade

- custom_components/midea_ac/manifest.json
Latest release adds support for Cascade
> Bump msmart-ng to 2025.7.0

- custom_components/midea_ac/translations/bg.json
- custom_components/midea_ac/translations/ca.json
- custom_components/midea_ac/translations/cs.json
- custom_components/midea_ac/translations/de.json
- custom_components/midea_ac/translations/es.json
- custom_components/midea_ac/translations/eu.json
- custom_components/midea_ac/translations/fr.json
- custom_components/midea_ac/translations/hr.json
- custom_components/midea_ac/translations/hu.json
- custom_components/midea_ac/translations/it.json
- custom_components/midea_ac/translations/ko.json
- custom_components/midea_ac/translations/nb.json
- custom_components/midea_ac/translations/nl.json
- custom_components/midea_ac/translations/pl.json
- custom_components/midea_ac/translations/pt.json
- custom_components/midea_ac/translations/ro.json
- custom_components/midea_ac/translations/ru.json
- custom_components/midea_ac/translations/sk.json
- custom_components/midea_ac/translations/sl.json
- custom_components/midea_ac/translations/tr.json
- custom_components/midea_ac/translations/uk.json
- custom_components/midea_ac/translations/zh-Hans.json
- custom_components/midea_ac/translations/zh-Hant.json
I didn't have it translate any of the strings but had it update all translations so they have the correct structure. This should hopefully allow others to easily contribute updates.
> Update all translation files wih the "magic" of AI.

- .github/workflows/checks.yml
- .github/workflows/hacs.yml
- .github/workflows/hassfest.yml
To address new code scanning alerts
> Add workflow permissions
